loki:
  enabled: true
  isDefault: true
  ruler:
    storage:
      type: local
      local:
        directory: /rules
    rule_path: /tmp/scratch
    alertmanager_url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
    ring:
      kvstore:
        store: inmemory
    enable_api: true

  alerting_groups:
  - name: java-rules
    rules: 
    - alert: JavaException Rule
      expr:  | 
        {namespace="bozo-book-library-dev"} |= `ERROR`
      labels:
        application: 'bozobooks'
        source: 'java-exception'

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push

