apiVersion: v1
kind: ConfigMap
metadata:
  name: book-info-service-config-map
  namespace: {{.Values.namespace}}
data:
  quarkus.http.cors: "true"
  quarkus.http.cors.origins: "*"
  quarkus.http.cors.headers: "accept, authorization, content-type, x-requested-with"
  quarkus.http.cors.methods: "GET, OPTIONS, POST"
  quarkus.redis.hosts: {{.Values.book-library-service.database.redis-host}}
  book.info.service.google.book.api.url: {{.Values.book-info-service.google-api-url}}
  book.info.service.max.results.per.page: {{.Values.bozobooks-ui-service.results-per-page}}

