apiVersion: v1
kind: ServiceAccount
metadata:
  name: bozobooks-app
  namespace: {{.Values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bozobooks-cluster-role
  namespace: {{.Values.namespace}}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bozobooks-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: bozobooks-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: bozobooks-app
    namespace: {{.Values.namespace}}