kind: PersistentVolume
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-volume
  namespace: bozo-book-library-dev
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-claim
  namespace: bozo-book-library-dev
  labels:
    app: book-library-postgres-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi