loki:
  enabled: true
  isDefault: true
  persistence:
    enables: true
    storageClassName: local-storage
    size: 1Gi

promtail:
  enabled: true

additionalPrometheusRules:
  - name: error-alert
    groups:
    - name: error-logs
      rules:
      - alert: bozo-book-lib-errors
        expr: "container_memory_usage_bytes{namespace=\"bozo-book-library-dev\"}"
        for: 2m
        annotations:
          message: 'Error ({{ $value }}).'

