apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: redis-exporter
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_ADDR
          value:  redis-cluster.foo.svc:6379
        ports:
        - containerPort: 9121

---
apiVersion: v1
kind: Service
metadata:
  name: redis-external-exporter
  namespace: monitoring
  labels:
    app: redis
    k8s-app: redis-ext
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "9121"
spec:
  ports:
  - name: redis-ext
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: redis-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bozo-book-lib-svc-mon
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      application: bozo-book-library 
      release: prometheus
  endpoints:
  - interval: 15s
    path: /metrics   
    port: "9121"
  namespaceSelector:
    any: true
