apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prom-pm-bozo-book-lib
  namespace: monitoring
  labels:
    name: prometheus
spec:
  selector:
    matchLabels:
      application: bozo-book-library
  namespaceSelector:
    any: true

  podMetricsEndpoints:
  - port: web