apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: bozo-book-library-dev
spec:
  vault:
    server: http://vault.vault.svc.cluster.local:8200
    path: pki/sign/bozobooks-dot-com
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: issuer-token
          key: token