apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---


kind: PersistentVolume
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  local:
    path: "/Users/vijaykumarab/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-claim
  namespace: bozo-book-library-dev
  labels:
    app: book-library-postgres-db
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi