apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    name: prometheus
spec:
  selector:
    matchLabels:
       application: bozo-book-library
  namespaceSelector:
    any: true
  endpoints:
    - port: web