kind: PersistentVolume
apiVersion: v1
metadata:
  name: book-library-postgres-db-pv-volume
  labels:
    type: ibm-cloud
    app: book-library-postgres-db
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
