apiVersion: v1
kind: ServiceAccount
metadata:
  name: bozo-book-library-sa
  namespace: bozo-book-library-dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bozo-book-library-role
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: bozo-book-library-sa
    namespace: bozo-book-library-dev
