apiVersion: v1
kind: Service
metadata:
  name: book-library-ui-svc
  namespace: bozo-book-library-dev
  labels: 
    application: bozo-book-library
spec:
  selector: 
    app: book-library-ui-service
  
  ports:
    - name: http
      port: 80
      targetPort: 80
    
  
