apiVersion: v1
kind: Service
metadata:
  name: book-library-service-svc
  namespace: bozo-book-library-dev
  labels: 
    application: bozo-book-library
spec:
  selector: 
    app: book-library-service
  
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    
  
