apiVersion: v1
kind: Service
metadata:
  name: book-library-postgres-db-svc
  namespace: bozo-book-library-dev
  labels:
    app: book-library-postgres-db-svc
    application: bozo-book-library
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: book-library-postgres-db