apiVersion: v1
kind: ConfigMap
metadata:
  name:  book-library-postgres-db-config
  namespace: bozo-book-library-dev
  labels:
    app: book-library-postgres-db
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: ""