# This is a basic workflow to help you get started with Actions

name: Deply Book Info Service with the update on Build Number

# Controls when the workflow will run
on:
  repository_dispatch:
    types: deploy-book-info-service-infra-updated-build
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      # Runs a set of commands using the runners shell
      - name: Update the Build number
        run: |
          echo "Updating the Build Number: ${{github.event.client_payload.buildnumber}}"

      - name: Update Image Version in the yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/deployment-manifests/book-info-service-deployment.yaml'
          propertyPath: 'spec.template.spec.containers[1].image'
          value: 'abvijaykumar/bozo-book-info-service:${{github.event.client_payload.buildnumber}}'
          token: ${{secrets.API_TOKEN_GITHUB}}
          masterBranchName: 'main'
          branch: 'main'
          targetBranch: 'main'
          message: 'Update Image Version to abvijaykumar/bozo-book-info-service:${{github.event.client_payload.buildnumber}} ' 
