
name: Book UI Service Build Number in K8s Manifest

# Controls when the workflow will run
on:
  repository_dispatch:
    types: update-book-ui-service-build-number

jobs:
  DevDeploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Update the Build number
        run: |
          echo "Updating the Build Number: ${{github.event.client_payload.buildnumber}}"

      - name: Update Image Version in the yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev/bozobooks-manifests/deployment-manifests/book-library-ui-deployment.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: 'abvijaykumar/bozo-book-library-ui-service:${{ github.event.client_payload.buildnumber}}'
          masterBranchName: 'main'
          branch: 'main'
          message: 'Update Image Version to abvijaykumar/bozo-book-library-ui-service:${{ github.event.client_payload.buildnumber }}' 
  
